/* config.h -- generated by configure */
#ifndef CONFIG_H
#define CONFIG_H


#define SIZE_T_STDDEF_H 1
#define NO_FPRINTF_IN_STDIO 1
#define NO_SPRINTF_IN_STDIO 1

#define HAVE_REAL_PIPES 1
#endif /* CONFIG_H */
